// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(LootContext))]
    [Migration("20230827042748_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Coin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Half Copper"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Copper"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nickel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Electrum"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Platinum"
                        });
                });

            modelBuilder.Entity("Data.Entities.CoinResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<int>("Rolls")
                        .HasColumnType("integer");

                    b.Property<int>("Sides")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.ToTable("CoinResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoinId = 3,
                            Level = 1,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 2,
                            CoinId = 4,
                            Level = 1,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 6
                        },
                        new
                        {
                            Id = 3,
                            CoinId = 5,
                            Level = 1,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 4,
                            CoinId = 7,
                            Level = 1,
                            Multiplier = 10,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 5,
                            CoinId = 8,
                            Level = 1,
                            Multiplier = 10,
                            Rolls = 1,
                            Sides = 4
                        },
                        new
                        {
                            Id = 6,
                            CoinId = 3,
                            Level = 2,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 10
                        },
                        new
                        {
                            Id = 7,
                            CoinId = 4,
                            Level = 2,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 8,
                            CoinId = 5,
                            Level = 2,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 10
                        },
                        new
                        {
                            Id = 9,
                            CoinId = 7,
                            Level = 2,
                            Multiplier = 10,
                            Rolls = 3,
                            Sides = 10
                        },
                        new
                        {
                            Id = 10,
                            CoinId = 8,
                            Level = 2,
                            Multiplier = 10,
                            Rolls = 1,
                            Sides = 6
                        },
                        new
                        {
                            Id = 11,
                            CoinId = 3,
                            Level = 3,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 10
                        },
                        new
                        {
                            Id = 12,
                            CoinId = 4,
                            Level = 3,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 13,
                            CoinId = 5,
                            Level = 3,
                            Multiplier = 1000,
                            Rolls = 1,
                            Sides = 6
                        },
                        new
                        {
                            Id = 14,
                            CoinId = 7,
                            Level = 3,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 15,
                            CoinId = 8,
                            Level = 3,
                            Multiplier = 10,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 16,
                            CoinId = 3,
                            Level = 4,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 17,
                            CoinId = 4,
                            Level = 4,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 18,
                            CoinId = 5,
                            Level = 4,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 19,
                            CoinId = 7,
                            Level = 4,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 20,
                            CoinId = 8,
                            Level = 4,
                            Multiplier = 10,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 21,
                            CoinId = 3,
                            Level = 5,
                            Multiplier = 1000,
                            Rolls = 5,
                            Sides = 10
                        },
                        new
                        {
                            Id = 22,
                            CoinId = 4,
                            Level = 5,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 23,
                            CoinId = 5,
                            Level = 5,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 24,
                            CoinId = 7,
                            Level = 5,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 25,
                            CoinId = 8,
                            Level = 5,
                            Multiplier = 10,
                            Rolls = 2,
                            Sides = 10
                        },
                        new
                        {
                            Id = 26,
                            CoinId = 3,
                            Level = 6,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 27,
                            CoinId = 4,
                            Level = 6,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 6
                        },
                        new
                        {
                            Id = 28,
                            CoinId = 5,
                            Level = 6,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 29,
                            CoinId = 7,
                            Level = 6,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 30,
                            CoinId = 8,
                            Level = 6,
                            Multiplier = 10,
                            Rolls = 3,
                            Sides = 6
                        },
                        new
                        {
                            Id = 31,
                            CoinId = 3,
                            Level = 7,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 32,
                            CoinId = 4,
                            Level = 7,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 8
                        },
                        new
                        {
                            Id = 33,
                            CoinId = 5,
                            Level = 7,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 6
                        },
                        new
                        {
                            Id = 34,
                            CoinId = 7,
                            Level = 7,
                            Multiplier = 100,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 35,
                            CoinId = 8,
                            Level = 7,
                            Multiplier = 10,
                            Rolls = 4,
                            Sides = 6
                        },
                        new
                        {
                            Id = 36,
                            CoinId = 3,
                            Level = 8,
                            Multiplier = 10000,
                            Rolls = 3,
                            Sides = 6
                        },
                        new
                        {
                            Id = 37,
                            CoinId = 4,
                            Level = 8,
                            Multiplier = 1000,
                            Rolls = 6,
                            Sides = 8
                        },
                        new
                        {
                            Id = 38,
                            CoinId = 5,
                            Level = 8,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 39,
                            CoinId = 7,
                            Level = 8,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 8
                        },
                        new
                        {
                            Id = 40,
                            CoinId = 8,
                            Level = 8,
                            Multiplier = 10,
                            Rolls = 5,
                            Sides = 8
                        },
                        new
                        {
                            Id = 41,
                            CoinId = 3,
                            Level = 9,
                            Multiplier = 10000,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 42,
                            CoinId = 4,
                            Level = 9,
                            Multiplier = 1000,
                            Rolls = 6,
                            Sides = 8
                        },
                        new
                        {
                            Id = 43,
                            CoinId = 5,
                            Level = 9,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 6
                        },
                        new
                        {
                            Id = 44,
                            CoinId = 7,
                            Level = 9,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 8
                        },
                        new
                        {
                            Id = 45,
                            CoinId = 8,
                            Level = 9,
                            Multiplier = 10,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 46,
                            CoinId = 4,
                            Level = 10,
                            Multiplier = 10000,
                            Rolls = 1,
                            Sides = 6
                        },
                        new
                        {
                            Id = 47,
                            CoinId = 5,
                            Level = 10,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 48,
                            CoinId = 7,
                            Level = 10,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 12
                        },
                        new
                        {
                            Id = 49,
                            CoinId = 8,
                            Level = 10,
                            Multiplier = 10,
                            Rolls = 5,
                            Sides = 10
                        },
                        new
                        {
                            Id = 50,
                            CoinId = 4,
                            Level = 11,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 51,
                            CoinId = 5,
                            Level = 11,
                            Multiplier = 1000,
                            Rolls = 5,
                            Sides = 10
                        },
                        new
                        {
                            Id = 52,
                            CoinId = 7,
                            Level = 11,
                            Multiplier = 100,
                            Rolls = 5,
                            Sides = 12
                        },
                        new
                        {
                            Id = 53,
                            CoinId = 8,
                            Level = 11,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 54,
                            CoinId = 4,
                            Level = 12,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 55,
                            CoinId = 5,
                            Level = 12,
                            Multiplier = 1000,
                            Rolls = 5,
                            Sides = 10
                        },
                        new
                        {
                            Id = 56,
                            CoinId = 7,
                            Level = 12,
                            Multiplier = 1000,
                            Rolls = 1,
                            Sides = 6
                        },
                        new
                        {
                            Id = 57,
                            CoinId = 8,
                            Level = 12,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 58,
                            CoinId = 5,
                            Level = 13,
                            Multiplier = 1000,
                            Rolls = 1,
                            Sides = 6
                        },
                        new
                        {
                            Id = 59,
                            CoinId = 7,
                            Level = 13,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 60,
                            CoinId = 8,
                            Level = 13,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 61,
                            CoinId = 5,
                            Level = 14,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 4
                        },
                        new
                        {
                            Id = 62,
                            CoinId = 7,
                            Level = 14,
                            Multiplier = 1000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 63,
                            CoinId = 8,
                            Level = 14,
                            Multiplier = 100,
                            Rolls = 2,
                            Sides = 8
                        },
                        new
                        {
                            Id = 64,
                            CoinId = 5,
                            Level = 15,
                            Multiplier = 10000,
                            Rolls = 2,
                            Sides = 6
                        },
                        new
                        {
                            Id = 65,
                            CoinId = 7,
                            Level = 15,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 6
                        },
                        new
                        {
                            Id = 67,
                            CoinId = 8,
                            Level = 15,
                            Multiplier = 100,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 68,
                            CoinId = 5,
                            Level = 16,
                            Multiplier = 10000,
                            Rolls = 3,
                            Sides = 6
                        },
                        new
                        {
                            Id = 69,
                            CoinId = 7,
                            Level = 16,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 70,
                            CoinId = 8,
                            Level = 16,
                            Multiplier = 100,
                            Rolls = 3,
                            Sides = 10
                        },
                        new
                        {
                            Id = 71,
                            CoinId = 5,
                            Level = 17,
                            Multiplier = 10000,
                            Rolls = 3,
                            Sides = 8
                        },
                        new
                        {
                            Id = 72,
                            CoinId = 7,
                            Level = 17,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 10
                        },
                        new
                        {
                            Id = 73,
                            CoinId = 8,
                            Level = 17,
                            Multiplier = 100,
                            Rolls = 3,
                            Sides = 12
                        },
                        new
                        {
                            Id = 74,
                            CoinId = 5,
                            Level = 18,
                            Multiplier = 10000,
                            Rolls = 3,
                            Sides = 10
                        },
                        new
                        {
                            Id = 75,
                            CoinId = 7,
                            Level = 18,
                            Multiplier = 1000,
                            Rolls = 3,
                            Sides = 12
                        },
                        new
                        {
                            Id = 76,
                            CoinId = 8,
                            Level = 18,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 77,
                            CoinId = 5,
                            Level = 19,
                            Multiplier = 10000,
                            Rolls = 4,
                            Sides = 8
                        },
                        new
                        {
                            Id = 78,
                            CoinId = 7,
                            Level = 19,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 79,
                            CoinId = 8,
                            Level = 19,
                            Multiplier = 100,
                            Rolls = 4,
                            Sides = 12
                        },
                        new
                        {
                            Id = 80,
                            CoinId = 5,
                            Level = 20,
                            Multiplier = 10000,
                            Rolls = 4,
                            Sides = 10
                        },
                        new
                        {
                            Id = 81,
                            CoinId = 7,
                            Level = 20,
                            Multiplier = 1000,
                            Rolls = 4,
                            Sides = 12
                        },
                        new
                        {
                            Id = 82,
                            CoinId = 8,
                            Level = 20,
                            Multiplier = 100,
                            Rolls = 5,
                            Sides = 10
                        });
                });

            modelBuilder.Entity("Data.Entities.CoinResults", b =>
                {
                    b.HasOne("Data.Entities.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("CoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coin");
                });
#pragma warning restore 612, 618
        }
    }
}
